name: .NET Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        configuration: [ Debug, Release ]

    env:
      Project_Path: NoVSync.csproj

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ${{ env.Project_Path }}

      - name: Build (${{ matrix.configuration }})
        run: dotnet build ${{ env.Project_Path }} --configuration ${{ matrix.configuration }} --no-restore

      - name: Test (${{ matrix.configuration }})
        run: dotnet test ${{ env.Project_Path }} --configuration ${{ matrix.configuration }} --no-build --verbosity normal

      - name: Upload build artifacts (${{ matrix.configuration }})
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.configuration }}
          path: |
            bin/${{ matrix.configuration }}/
