release:
  needs: build
  runs-on: ubuntu-latest
  if: startsWith(github.ref, 'refs/tags/')

  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download Release artifact
      uses: actions/download-artifact@v4
      with:
        name: build-Release
        path: release-build

    - name: Prepare mod folder
      run: |
        mkdir -p NoVSync
        cp release-build/NoVSync.dll NoVSync/
        cp manifest.json NoVSync/   # assumes manifest.json is in repo root

    - name: Create zip package
      run: |
        zip -r NoVSync-${GITHUB_REF_NAME}.zip NoVSync/

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: NoVSync-${{ github.ref_name }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
