name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: YourSolution.sln              # Replace with your actual .sln file
      Wap_Project_Path: path/to/YourApp.csproj     # Replace with path to your project

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x                      # Adjust if using a different version

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet packages
      run: msbuild ${{ env.Solution_Name }} /t:Restore /p:Configuration=${{ matrix.configuration }}

    - name: Build the solution
      run: msbuild ${{ env.Solution_Name }} /p:Configuration=${{ matrix.configuration }}

    - name: Publish the app
      run: |
        dotnet publish ${{ env.Wap_Project_Path }} --configuration ${{ matrix.configuration }} --output ./publish
